[package]
authors = ["Zeyla Hellyer <zeyla@hellyer.dev>"]
documentation = "https://docs.rs/dawn-command-parser"
edition = "2018"
homepage = "https://github.com/dawn-rs/dawn"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "dawn"]
license = "ISC"
name = "dawn-command-parser"
publish = false
readme = "README.md"
repository = "https://github.com/dawn-rs/dawn.git"
version = "0.1.0"

[dependencies]
unicase = "2"
